version: '3.9'
services:
  php:
    container_name: php
    build: ./docker/php
    volumes: 
    - ./src:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
     - 80:80
    volumes:
    - ./src:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kazuki6061
      MYSQL_DATABASE: focus
      MYSQL_USER: kazuki
      MYSQL_PASSWORD: 25251061k
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: php-myadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=kazuki
      - PMA_PASSWORD=25251061k
    ports: 
    - 4040:80
